version: 2
updates:
  # Configure updates for Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "main"  # or your default branch name
    labels:
      - "dependencies"
      - "android"
    
  # Configure updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: ".github/worfklows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  